-- =====================================================
-- 记账系统数据库表结构
-- 执行位置：Supabase控制台 -> SQL编辑器
-- =====================================================

-- 1. 员工表
CREATE TABLE employees (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) NOT NULL UNIQUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. 产品表（计件单价）
CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(100) NOT NULL,
  name VARCHAR(100) NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. 销售记录表
CREATE TABLE sales_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id BIGINT REFERENCES employees(id),
  product_id BIGINT REFERENCES products(id),
  record_date DATE NOT NULL,
  quantity INTEGER NOT NULL DEFAULT 1,
  unit_price DECIMAL(10,2) NOT NULL,
  total_amount DECIMAL(10,2) NOT NULL,
  is_return BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. 创建索引
CREATE INDEX idx_sales_date ON sales_records(record_date);
CREATE INDEX idx_sales_employee ON sales_records(employee_id);
CREATE INDEX idx_products_code ON products(code);
CREATE INDEX idx_products_name ON products(name);

-- =====================================================
-- 初始化数据（可选，可删除）
-- =====================================================

-- 初始化员工数据
INSERT INTO employees (name) VALUES
('郭美丽'), ('林连治'), ('廖永丽'), ('周水锦'), ('王雪娥');

-- 初始化产品数据
INSERT INTO products (code, name, price) VALUES
('备菜架', '备菜架', 0.40),
('迷齐边几30', '迷齐边几30', 3.00),
('迷齐边几35', '迷齐边几35', 3.50),
('迷齐边几40', '迷齐边几40', 4.00),
('猫头鞋架', '猫头鞋架', 0.50),
('猫头鞋架3件', '猫头鞋架（3件装）', 1.50),
('猫头鞋架6件', '猫头鞋架（6件装）', 3.00),
('猫头鞋架9件', '猫头鞋架（9件装）', 4.50),
('猫头鞋架12件', '猫头鞋架（12件装）', 6.00),
('猫头鞋架15件', '猫头鞋架（15件装）', 7.50),
('猫头鞋架18件', '猫头鞋架（18件装）', 9.00);

-- =====================================================
-- 验证创建结果
-- =====================================================

-- 查看所有表
SELECT table_name FROM information_schema.tables WHERE table_schema = 'public';

-- 查看员工数据
SELECT * FROM employees;

-- 查看产品数据
SELECT * FROM products;
